extends:
- file: hashstack/linux.yaml

package_dirs:
- pkgs
- hashstack


packages:
  cmake:
  mpi:
    #use: host-mpi
    use: mpich
  blas:
    use: openblas
  lapack:
    use: openblas
  hypre:
    with_openblas: true
    without_check: true
  petsc:
    build_with: |
      openblas, hypre
#, parmetis, scotch, suitesparse, superlu_dist, hypre
#    download: |
#      mumps, scalapack, blacs, ml
    coptflags: -O2
    link: shared
    debug: true
  dealii:
    build_with: petsc
